# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 20m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
    - unused
    - staticcheck
    - bidichk
    - durationcheck
    - exportloopref
    - whitespace
    - revive
    - gosec
    - gofmt

linters-settings:
  gofmt:
    simplify: true
  revive:
    enable-all-rules: false
    rules:
      - name: receiver-naming
        severity: warning
        disabled: false
        exclude: [""]
